# trelix funding configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [sairam0424]
# open_collective: trelix
# ko_fi: trelix
# custom: ["https://trelix.dev/sponsor"]
