"""Exact oracle for ``HtmlParser._count_errors`` -> ``ParseResult.parse_errors``.

Mutation-verified. ``_count_errors`` -> ``count = 0`` survived 151 tests
(``test_parser_html_symbol_set_oracle``, ``test_parser_module_symbol_set_oracle``,
``test_parser_zero_coverage``, ``test_indexer_core``, ``test_api``,
``test_line_window_parser``) and 808 tests across the whole ``-k "html or parser
or parse or indexer"`` slice. It survived because every HTML assertion on this
field was ``parse_errors == 0`` on well-formed input, and ``0 == 0`` holds for a
function that can only ever return zero. ``parse_errors`` is what the indexer
reports to the user about a file it could not fully understand, so a
permanently-zero count means malformed HTML is indexed as though it parsed
cleanly and nothing anywhere says otherwise.

Two traps this file is shaped around:

1. Unclosed tags are NOT malformed to tree-sitter-html. Measured on this tree,
   ``<div><p>hello</div>`` yields ``root.has_error is False`` and ZERO ERROR
   nodes -- the grammar closes them implicitly. A fixture built only from
   unclosed tags cannot kill this mutant. ``MALFORMED_HTML`` line 8 keeps an
   unclosed ``<p>`` precisely to document that it contributes nothing.
2. A stray ``<`` in text (line 11, ``a < b``) sets ``root.has_error`` but
   produces a MISSING ``>`` node rather than an ERROR node, and MISSING nodes
   are not counted. See the documented-gap test at the bottom.

Every expected value below is a hand-written LITERAL derived by reading the
parse tree, not by calling the function under test. ``_walk_error_nodes`` is an
independent, test-local reimplementation used ONLY as a fixture precondition --
never as the source of an expected number -- so that a tree-sitter grammar bump
that changes the fixture's error shape fails loudly and by name instead of
silently making these assertions vacuous.
"""

from __future__ import annotations

import pytest
from tree_sitter import Node

from trelix.indexing.parser.extractors.html import HtmlParser

FILE_ID = 11

# ---------------------------------------------------------------------------
# Fixtures. Line numbers are load-bearing -- the expected tables below cite
# them -- so do not reflow these strings.
# ---------------------------------------------------------------------------

# 1  <!DOCTYPE html>
# 2  <html>
# 3  <head>
# 4    <title>Broken Page</title>
# 5  </head>
# 6  <body>
# 7    <div id="wrapper">
# 8      <p>unclosed paragraph          <- unclosed: contributes NO error node
# 9      <span data-x=>...              <- bare "=" with no value: 1 ERROR
# 10     <section "orphan">ok</section>  <- quoted orphan attr: 1 ERROR + 1 nested
# 11     <footer>a < b ...</footer>      <- stray "<": MISSING ">", NOT an ERROR
# 12     <em>tail</em> <                 <- lone trailing "<": 1 ERROR
# 13   </div>
# 14 </body>
# 15 </html>
MALFORMED_HTML = """\
<!DOCTYPE html>
<html>
<head>
  <title>Broken Page</title>
</head>
<body>
  <div id="wrapper">
    <p>unclosed paragraph
    <span data-x=>equals with no value</span>
    <section "orphan">ok</section>
    <footer>a < b and a lone bracket next</footer>
    <em>tail</em> <
  </div>
</body>
</html>
"""

# Structurally identical to MALFORMED_HTML with each defect repaired, so the
# zero-error direction is tested against the same shape of document rather than
# against a trivially small one.
WELL_FORMED_HTML = """\
<!DOCTYPE html>
<html>
<head>
  <title>Good Page</title>
  <meta name="description" content="fine">
</head>
<body>
  <div id="wrapper">
    <p>a closed paragraph</p>
    <span data-x="1">value present</span>
    <section id="s1">ok</section>
    <footer>a and b</footer>
    <em>tail</em>
  </div>
</body>
</html>
"""

# Only unclosed tags. Deliberately NOT used to assert a positive count: it is
# here to pin the trap in this file's docstring.
UNCLOSED_ONLY_HTML = "<div><p>hello</div>"


# Every ERROR node the tree-sitter-html grammar produces for MALFORMED_HTML,
# read off the parse tree by hand as (1-based line, 0-based column, source text).
# Written out one row at a time -- this table is NOT generated by iterating the
# tree, because generating it is what would let a row silently disappear.
EXPECTED_MALFORMED_ERROR_NODES = frozenset(
    {
        (9, 16, "="),  # <span data-x=>  -- "=" with no attribute value
        (10, 13, '"orphan"'),  # <section "orphan">  -- outer ERROR spanning the quotes
        (10, 14, "orphan"),  # ...and the ERROR nested INSIDE it
        (12, 18, "<"),  # <em>tail</em> <  -- lone trailing bracket
    }
)

# Hand-written literal, not len(EXPECTED_MALFORMED_ERROR_NODES) and not taken
# from HtmlParser. The assertion below ties the two together so they cannot drift.
EXPECTED_MALFORMED_PARSE_ERRORS = 4

# Of the four, three are top-level (not inside another ERROR). The total being 4
# rather than 3 is the only thing that pins the recursive descent.
EXPECTED_MALFORMED_TOP_LEVEL_ERROR_NODES = 3


@pytest.fixture()
def html() -> HtmlParser:
    return HtmlParser()


def _walk_error_nodes(node: Node, src: bytes) -> list[tuple[int, int, str]]:
    """Independent ERROR-node walker used ONLY for fixture preconditions.

    Deliberately not imported from and not shared with HtmlParser._count_errors.
    Its output is never used as an expected value -- only compared against the
    literal tables above.
    """
    found: list[tuple[int, int, str]] = []
    if node.type == "ERROR":
        found.append(
            (
                node.start_point[0] + 1,
                node.start_point[1],
                src[node.start_byte : node.end_byte].decode("utf-8", errors="replace"),
            )
        )
    for child in node.children:
        found.extend(_walk_error_nodes(child, src))
    return found


def _parse_tree_error_nodes(source: str) -> list[tuple[int, int, str]]:
    src = source.encode("utf-8")
    root = HtmlParser()._parser.parse(src).root_node
    return _walk_error_nodes(root, src)


def _root(source: str) -> Node:
    return HtmlParser()._parser.parse(source.encode("utf-8")).root_node


# ===========================================================================
# Preconditions -- these fail, naming the fixture, the moment a fixture stops
# discriminating. Without them a grammar change could make the real assertions
# below true by construction.
# ===========================================================================


def test_precondition_malformed_fixture_really_produces_error_nodes() -> None:
    """Guards MALFORMED_HTML against becoming well-formed under a grammar bump.

    Not a mutation test -- it never calls _count_errors. If tree-sitter-html
    stops emitting exactly these ERROR nodes, the exact-count assertion below
    would be pinning the wrong number, so fail here first and by name.
    """
    actual = _parse_tree_error_nodes(MALFORMED_HTML)

    assert len(EXPECTED_MALFORMED_ERROR_NODES) == EXPECTED_MALFORMED_PARSE_ERRORS, (
        "the ERROR-node table and the expected count have drifted apart"
    )
    # Set equality BOTH ways: a new ERROR node fails as loudly as a missing one.
    assert set(actual) == EXPECTED_MALFORMED_ERROR_NODES, (
        "MALFORMED_HTML no longer produces exactly the ERROR nodes this file "
        f"pins; the tree-sitter-html grammar shape changed. got={sorted(actual)} "
        f"expected={sorted(EXPECTED_MALFORMED_ERROR_NODES)}"
    )
    assert len(actual) == EXPECTED_MALFORMED_PARSE_ERRORS, (
        f"MALFORMED_HTML must contain {EXPECTED_MALFORMED_PARSE_ERRORS} ERROR "
        f"nodes for the exact-count oracle to mean anything; got {len(actual)}"
    )


def test_precondition_well_formed_fixture_is_genuinely_error_free() -> None:
    """Guards WELL_FORMED_HTML: makes the ``== 0`` direction non-vacuous.

    Not a mutation test. ``parse_errors == 0`` is exactly the assertion the
    surviving mutant satisfies for free, so the zero must be corroborated
    against the tree itself (``root.has_error``, a tree-sitter property that
    _count_errors has no influence over) rather than trusted on its own.
    """
    root = _root(WELL_FORMED_HTML)
    assert root.has_error is False, (
        "WELL_FORMED_HTML is no longer well-formed to tree-sitter-html, so the "
        "zero-error assertion below would pass for the wrong reason"
    )
    assert _parse_tree_error_nodes(WELL_FORMED_HTML) == [], (
        "WELL_FORMED_HTML must contain no ERROR nodes"
    )


def test_precondition_unclosed_tags_alone_are_not_errors() -> None:
    """Pins the trap: unclosed tags produce NO ERROR nodes in tree-sitter-html.

    Not a mutation test. It exists so that anyone widening these fixtures learns
    from a failing assertion, not from a green mutant, that "malformed HTML"
    built only from unclosed tags cannot exercise _count_errors at all.
    """
    root = _root(UNCLOSED_ONLY_HTML)
    assert root.has_error is False, (
        "UNCLOSED_ONLY_HTML now reports a tree error; the documented trap in "
        "this module's docstring needs revisiting"
    )
    assert _parse_tree_error_nodes(UNCLOSED_ONLY_HTML) == []


# ===========================================================================
# The oracle. Discriminates in BOTH directions.
# ===========================================================================


def test_malformed_html_reports_exact_nonzero_parse_error_count(html: HtmlParser) -> None:
    """Kills ``_count_errors``: ``count = 1 if node.type == "ERROR" else 0`` -> ``count = 0``.

    Also kills deletion of the ``for child in node.children: count +=
    self._count_errors(child)`` recursion: the root node is not itself an ERROR,
    so without the recursion the result is 0, and a single-level count is 3
    (one of the four ERROR nodes is nested inside another), not 4.
    """
    result = html.parse(MALFORMED_HTML, file_id=FILE_ID)

    # The headline claim: malformed HTML must not be reported as clean.
    assert result.parse_errors > 0, (
        "malformed HTML reported zero parse errors -- the indexer would present "
        "this file as fully understood"
    )
    # The exact count, as a literal. This is what makes the test an oracle
    # rather than a smoke test, and what pins the recursive descent.
    assert result.parse_errors == EXPECTED_MALFORMED_PARSE_ERRORS
    assert result.parse_errors != EXPECTED_MALFORMED_TOP_LEVEL_ERROR_NODES, (
        "count matches the number of top-level ERROR nodes, so the nested "
        "ERROR node is no longer being counted: the recursion is gone"
    )


def test_well_formed_html_reports_exactly_zero_parse_errors(html: HtmlParser) -> None:
    """The other direction, so the test discriminates rather than only detecting.

    Does NOT kill ``count = 0`` on its own -- nothing asserting ``== 0`` can,
    which is why the mutant survived 808 tests. It is here so that a "fix" that
    inflates every count (for example ``count = 1`` unconditionally, or counting
    MISSING nodes as errors) cannot pass by satisfying the malformed case alone.
    """
    result = html.parse(WELL_FORMED_HTML, file_id=FILE_ID)

    assert result.parse_errors == 0


def test_unclosed_tags_alone_report_zero_parse_errors(html: HtmlParser) -> None:
    """Companion to the unclosed-tags precondition: 0 here is CORRECT, not a bug.

    tree-sitter-html closes the tags implicitly, so there is genuinely nothing
    to report. Does not kill the mutant; documents why a naive fixture cannot.
    """
    result = html.parse(UNCLOSED_ONLY_HTML, file_id=FILE_ID)

    assert result.parse_errors == 0


# ===========================================================================
# Documented gap -- pins CURRENT behaviour that is arguably a defect.
# ===========================================================================


def test_stray_lt_in_text_sets_tree_error_but_is_not_counted(html: HtmlParser) -> None:
    """DOCUMENTED GAP, not an endorsement. Pins current, arguably-wrong behaviour.

    ``<div>a < b</div>`` makes tree-sitter set ``root.has_error`` (it inserts a
    MISSING ``>``) yet produces zero ERROR nodes, so ``_count_errors`` returns 0
    and the indexer reports this file as parsed cleanly. ``_count_errors``
    counts ERROR nodes only and ignores MISSING nodes.

    That divergence is a real reporting gap: ``root.has_error`` is True while
    ``parse_errors`` is 0. If ``_count_errors`` is ever changed to include
    MISSING nodes (or to use ``has_error``), this test SHOULD fail and should be
    updated rather than worked around. Does not kill the ``count = 0`` mutant.
    """
    source = "<div>a < b</div>"
    root = _root(source)

    # Precondition: the divergence still exists in this grammar version.
    assert root.has_error is True, (
        "the stray-'<' fixture no longer sets has_error; this documented gap "
        "may have closed and the test should be re-derived"
    )
    assert _parse_tree_error_nodes(source) == [], (
        "the stray-'<' fixture now produces ERROR nodes; re-derive this gap"
    )

    result = html.parse(source, file_id=FILE_ID)

    assert result.parse_errors == 0
